Repository ionic-team/stencil, pull requests merged in 2021-09, with the labels that each got.

#3077 chore(sourcemaps): create linker string util
  src/compiler/output-targets/dist-custom-elements-bundle/index.ts
  src/compiler/output-targets/dist-custom-elements/index.ts
  src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
  src/compiler/output-targets/dist-lazy/write-lazy-entry-module.ts
  src/compiler/transpile.ts
  src/utils/sourcemaps.ts
  src/utils/test/sourcemaps.spec.ts
Labels: Feature: Sourcemaps

#3078 chore(fixups): minor sourcemap fixups
  src/compiler/app-core/bundle-app-core.ts
  src/compiler/output-targets/dist-collection/index.ts
  src/compiler/output-targets/dist-custom-elements-bundle/index.ts
  src/compiler/output-targets/dist-custom-elements/index.ts
  src/compiler/output-targets/dist-lazy/lazy-output.ts
  src/compiler/output-targets/output-collection.ts
  src/declarations/stencil-private.ts
Labels: Feature: Sourcemaps

#3030 fix: restore stats output target functionality.
  src/compiler/build/build-ctx.ts
  src/compiler/build/build-finish.ts
  src/compiler/build/build-stats.ts
  src/compiler/build/test/build-stats.spec.ts
  src/compiler/entries/component-graph.ts
  src/compiler/output-targets/dist-lazy/generate-cjs.ts
  src/compiler/output-targets/dist-lazy/generate-esm-browser.ts
  src/compiler/output-targets/dist-lazy/generate-esm.ts
  src/compiler/output-targets/dist-lazy/generate-lazy-module.ts
  src/compiler/output-targets/dist-lazy/generate-system.ts
  src/compiler/output-targets/dist-lazy/lazy-build-conditionals.ts
  src/compiler/output-targets/dist-lazy/lazy-component-plugin.ts
  src/compiler/output-targets/dist-lazy/lazy-output.ts
  src/compiler/output-targets/dist-lazy/write-lazy-entry-module.ts
  src/declarations/stencil-private.ts
  src/utils/byte-size.ts
  src/utils/index.ts
Labels: Resolution: Backlog

#3079 refactor(telemetry) Refactor out the singleton
  src/cli/ionic-config.ts
  src/cli/run.ts
  src/cli/state/stencil-cli-config.ts
  src/cli/state/test/stencil-cli-config.spec.ts
  src/cli/task-build.ts
  src/cli/task-help.ts
  src/cli/task-telemetry.ts
  src/cli/telemetry/helpers.ts
  src/cli/telemetry/shouldTrack.ts
  src/cli/telemetry/telemetry.ts
  src/cli/telemetry/test/helpers.spec.ts
  src/cli/telemetry/test/telemetry.spec.ts
  src/cli/test/ionic-config.spec.ts
  src/declarations/stencil-private.ts
  src/testing/index.ts
Labels: Maintainer Facing
